version: '3'

services:
    workspace:
        build:
            context: ..
            dockerfile: .devcontainer/Dockerfile
        volumes:
            - ..:/tf/work
        command: sleep infinity
        ulimits:
          memlock: -1
          stack: -1
        deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  capabilities: [ gpu ]
        tty: true
        expose:
          - "8888"
        ports:
          - "127.0.0.1:8888:8888"
        environment:
          - NVIDIA_VISIBLE_DEVICES=all
          - NVIDIA_DRIVER_CAPABILITIES=all
          - PYTHONPATH=/tf/work
